fix crash bug
Actually here check ACTION is not need anymore.
Notification always start setting activity not dimmer activity.

java.lang.RuntimeException: Unable to start activity
ComponentInfo{giraffine.dimmer/giraffine.dimmer.Dimmer}:
java.lang.NullPointerException
at
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2077)
at
android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2104)
at android.app.ActivityThread.access$600(ActivityThread.java:134)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1247)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:4624)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:809)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:576)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at giraffine.dimmer.Dimmer.onCreate(Dimmer.java:38)
at android.app.Activity.performCreate(Activity.java:4488)
at
android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1050)
at
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2041)
... 11 more